### ISSUE TITLE
[Feature] Pure ESM version

### ISSUE THREAD

**Issue by eolme** [ItzNeviKat/tiktok-bot#1]

**Comment by kosheeta** [comment]
Не вижу смысла в этом.

Запуск через `ts-node` действительно занимает больше времени из-за импортов. Но для меня это не критично при разработке, да и удобнее писать меньше букв при импорте.

Перед запуском на проде производится компиляция в JS и сразу же замена импортов на обычные, относительные. Поэтому скорость будет идентична.
